# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\tmlservice\"\x1f\n\x0bTrainingRow\x12\x10\n\x08\x66\x65\x61tures\x18\x01 \x03(\x02\"\xe0\x01\n\x0cTrainRequest\x12\x12\n\nmodel_type\x18\x01 \x01(\t\x12\x45\n\x0fhyperparameters\x18\x02 \x03(\x0b\x32,.mlservice.TrainRequest.HyperparametersEntry\x12-\n\rtraining_data\x18\x03 \x03(\x0b\x32\x16.mlservice.TrainingRow\x12\x0e\n\x06target\x18\x04 \x03(\x02\x1a\x36\n\x14HyperparametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"!\n\rTrainResponse\x12\x10\n\x08model_id\x18\x01 \x01(\t\"H\n\x0ePredictRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12$\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x16.mlservice.TrainingRow\"&\n\x0fPredictResponse\x12\x13\n\x0bpredictions\x18\x01 \x03(\x02\"\xa3\x01\n\x0eRetrainRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12G\n\x0fhyperparameters\x18\x02 \x03(\x0b\x32..mlservice.RetrainRequest.HyperparametersEntry\x1a\x36\n\x14HyperparametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"#\n\x0fRetrainResponse\x12\x10\n\x08model_id\x18\x01 \x01(\t\"!\n\rDeleteRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x07\n\x05\x45mpty\"\x1b\n\tModelList\x12\x0e\n\x06models\x18\x01 \x03(\t\" \n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x8d\x03\n\x0cModelService\x12?\n\nTrainModel\x12\x17.mlservice.TrainRequest\x1a\x18.mlservice.TrainResponse\x12\x33\n\tGetModels\x12\x10.mlservice.Empty\x1a\x14.mlservice.ModelList\x12@\n\x07Predict\x12\x19.mlservice.PredictRequest\x1a\x1a.mlservice.PredictResponse\x12\x45\n\x0cRetrainModel\x12\x19.mlservice.RetrainRequest\x1a\x1a.mlservice.RetrainResponse\x12\x42\n\x0b\x44\x65leteModel\x12\x18.mlservice.DeleteRequest\x1a\x19.mlservice.DeleteResponse\x12:\n\x0b\x43heckStatus\x12\x10.mlservice.Empty\x1a\x19.mlservice.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRAINREQUEST_HYPERPARAMETERSENTRY']._loaded_options = None
  _globals['_TRAINREQUEST_HYPERPARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_RETRAINREQUEST_HYPERPARAMETERSENTRY']._loaded_options = None
  _globals['_RETRAINREQUEST_HYPERPARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_TRAININGROW']._serialized_start=28
  _globals['_TRAININGROW']._serialized_end=59
  _globals['_TRAINREQUEST']._serialized_start=62
  _globals['_TRAINREQUEST']._serialized_end=286
  _globals['_TRAINREQUEST_HYPERPARAMETERSENTRY']._serialized_start=232
  _globals['_TRAINREQUEST_HYPERPARAMETERSENTRY']._serialized_end=286
  _globals['_TRAINRESPONSE']._serialized_start=288
  _globals['_TRAINRESPONSE']._serialized_end=321
  _globals['_PREDICTREQUEST']._serialized_start=323
  _globals['_PREDICTREQUEST']._serialized_end=395
  _globals['_PREDICTRESPONSE']._serialized_start=397
  _globals['_PREDICTRESPONSE']._serialized_end=435
  _globals['_RETRAINREQUEST']._serialized_start=438
  _globals['_RETRAINREQUEST']._serialized_end=601
  _globals['_RETRAINREQUEST_HYPERPARAMETERSENTRY']._serialized_start=232
  _globals['_RETRAINREQUEST_HYPERPARAMETERSENTRY']._serialized_end=286
  _globals['_RETRAINRESPONSE']._serialized_start=603
  _globals['_RETRAINRESPONSE']._serialized_end=638
  _globals['_DELETEREQUEST']._serialized_start=640
  _globals['_DELETEREQUEST']._serialized_end=673
  _globals['_DELETERESPONSE']._serialized_start=675
  _globals['_DELETERESPONSE']._serialized_end=708
  _globals['_EMPTY']._serialized_start=710
  _globals['_EMPTY']._serialized_end=717
  _globals['_MODELLIST']._serialized_start=719
  _globals['_MODELLIST']._serialized_end=746
  _globals['_STATUSRESPONSE']._serialized_start=748
  _globals['_STATUSRESPONSE']._serialized_end=780
  _globals['_MODELSERVICE']._serialized_start=783
  _globals['_MODELSERVICE']._serialized_end=1180
# @@protoc_insertion_point(module_scope)
